from __future__ import annotations

from pathlib import Path

from .convert import ConvertOptions


def options_to_dict(options: ConvertOptions) -> dict:
    return {
        "input_path": str(options.input_path),
        "output_path": str(options.output_path) if options.output_path else None,
        "output_format": options.output_format,
        "video_codec": options.video_codec,
        "audio_codec": options.audio_codec,
        "video_bitrate": options.video_bitrate,
        "audio_bitrate": options.audio_bitrate,
        "crf": options.crf,
        "preset": options.preset,
        "audio_stream": options.audio_stream,
        "video_stream": options.video_stream,
        "copy_streams": options.copy_streams,
        "overwrite": options.overwrite,
        "quality_preset_id": options.quality_preset_id,
        "scale": options.scale,
        "start_time": options.start_time,
        "end_time": options.end_time,
        "hardware_encode": options.hardware_encode,
        "prefer_hevc": options.prefer_hevc,
        "extract_audio": options.extract_audio,
        "extract_subtitles": options.extract_subtitles,
        "external_audio_path": str(options.external_audio_path) if options.external_audio_path else None,
        "subtitle_path": str(options.subtitle_path) if options.subtitle_path else None,
        "subtitle_stream": options.subtitle_stream,
        "subtitle_burn_in": options.subtitle_burn_in,
        "extract_subtitle_format": options.extract_subtitle_format,
        "normalize_audio": options.normalize_audio,
        "gif_mode": options.gif_mode,
        "metadata_title": options.metadata_title,
        "metadata_author": options.metadata_author,
        "metadata_date": options.metadata_date,
        "strip_metadata": options.strip_metadata,
        "verify_output": options.verify_output,
        "merge_inputs": [str(p) for p in options.merge_inputs],
        "crop": options.crop,
        "rotation": options.rotation,
        "fps": options.fps,
        "watermark_path": str(options.watermark_path) if options.watermark_path else None,
        "watermark_position": options.watermark_position,
        "two_pass": options.two_pass,
        "cover_art_path": str(options.cover_art_path) if options.cover_art_path else None,
        "preserve_chapters": options.preserve_chapters,
        "deinterlace": options.deinterlace,
        "denoise": options.denoise,
        "extra_audio_tracks": list(options.extra_audio_tracks),
        "replace_audio": options.replace_audio,
        "audio_delay_ms": options.audio_delay_ms,
    }


def options_from_dict(data: dict) -> ConvertOptions:
    def path_or_none(value: str | None) -> Path | None:
        return Path(value) if value else None

    merge = [Path(p) for p in data.get("merge_inputs") or []]
    return ConvertOptions(
        input_path=Path(data["input_path"]),
        output_path=path_or_none(data.get("output_path")),
        output_format=data.get("output_format"),
        video_codec=data.get("video_codec"),
        audio_codec=data.get("audio_codec"),
        video_bitrate=data.get("video_bitrate"),
        audio_bitrate=data.get("audio_bitrate"),
        crf=data.get("crf"),
        preset=data.get("preset", "medium"),
        audio_stream=data.get("audio_stream"),
        video_stream=data.get("video_stream"),
        copy_streams=bool(data.get("copy_streams")),
        overwrite=bool(data.get("overwrite")),
        quality_preset_id=data.get("quality_preset_id"),
        scale=data.get("scale"),
        start_time=data.get("start_time"),
        end_time=data.get("end_time"),
        hardware_encode=bool(data.get("hardware_encode")),
        prefer_hevc=bool(data.get("prefer_hevc")),
        extract_audio=bool(data.get("extract_audio")),
        extract_subtitles=bool(data.get("extract_subtitles")),
        external_audio_path=path_or_none(data.get("external_audio_path")),
        subtitle_path=path_or_none(data.get("subtitle_path")),
        subtitle_stream=data.get("subtitle_stream"),
        subtitle_burn_in=bool(data.get("subtitle_burn_in")),
        extract_subtitle_format=data.get("extract_subtitle_format") or "srt",
        normalize_audio=bool(data.get("normalize_audio")),
        gif_mode=bool(data.get("gif_mode")),
        metadata_title=data.get("metadata_title"),
        metadata_author=data.get("metadata_author"),
        metadata_date=data.get("metadata_date"),
        strip_metadata=bool(data.get("strip_metadata")),
        verify_output=bool(data.get("verify_output", True)),
        merge_inputs=merge,
        crop=data.get("crop"),
        rotation=data.get("rotation"),
        fps=data.get("fps"),
        watermark_path=path_or_none(data.get("watermark_path")),
        watermark_position=data.get("watermark_position") or "10:10",
        two_pass=bool(data.get("two_pass")),
        cover_art_path=path_or_none(data.get("cover_art_path")),
        preserve_chapters=bool(data.get("preserve_chapters", True)),
        deinterlace=bool(data.get("deinterlace")),
        denoise=bool(data.get("denoise")),
        extra_audio_tracks=list(data.get("extra_audio_tracks") or []),
        replace_audio=bool(data.get("replace_audio")),
        audio_delay_ms=int(data.get("audio_delay_ms") or 0),
    )
